# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-15 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
