# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-16 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0005_auto_20181115_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='message_id',
        ),
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default=0, max_length=45),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
