# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-16 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0006_auto_20181116_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_number',
        ),
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.CharField(default=0, max_length=45),
            preserve_default=False,
        ),
    ]
