# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-16 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginReg', '0001_initial'),
        ('postings', '0007_auto_20181116_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='LoginReg.User'),
            preserve_default=False,
        ),
    ]
